server:
  port: 8080 # The Gateway runs on the standard HTTP port 8080

spring:
  cloud:
    gateway:
      routes:
        - id: product-service-route
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**
          filters:
            - AuthenticationFilter

        - id: order-service-route
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - AuthenticationFilter

        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
          # no filter here so users can still reach the login endpoint
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

# list of URLs that do not require a token
app:
  permit-all:
    - /api/v1/users/login
    - /api/v1/users/register
    - /eureka/**