server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/ecommerce_order
    username: root
    password: Vansh@sql16
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      # using StringSerializer for keys and JsonSerializer for values to send JSON messages to Kafka
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics # exposes Actuator endpoints to check circuit state
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker: # configuration for Resilience4j Circuit Breaker
    instances: # define the circuit breaker instance for the inventory service
      inventory: # This is the custom name for our circuit breaker
        registerHealthIndicator: true
        slidingWindowSize: 5 # looks at the last 5 requests
        failureRateThreshold: 50 # if 50% (3 out of 5) fail, trip the breaker to OPEN
        waitDurationInOpenState: 5s # wait 5 seconds before switching to HALF-OPEN to test the target
        permittedNumberOfCallsInHalfOpenState: 3 # allow 3 test calls in HALF-OPEN state
        automaticTransitionFromOpenToHalfOpenEnabled: true # automatically transition from OPEN to HALF-OPEN after the wait duration
