server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_product
    username: root
    password: Vansh@sql16
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true