spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          # Points to your local config folder
          uri: file:///D:/Vansh/Projects/ecommerce-microservices-platform/config-repo
          clone-on-start: true

server:
  port: 8888